### ISSUE TITLE
BatchProfiler reports Complete, but is really a write_data_to_db error 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/BatchProfiler#22] opened 2016-01-11 16:49 UTC
[Batch 2](http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=2) on the docker BatchProfiler reports "Complete" but completed pretty quickly. Clicking on the [last txt output file](http://imagewebrhel6/batchprofiler/cgi-bin/ViewTextFile.py?batch_array_id=2&task_id=6&file_type=text) shows it is actually an ExportToDatabase write_data_to_db error.  

```
...
Mon Jan 11 11:40:40 2016: Image # 26, module SaveImages # 42: 0.80 sec
Mon Jan 11 11:40:40 2016: Image # 26, module SaveImages # 43: 0.45 sec
Mon Jan 11 11:40:41 2016: Image # 26, module SaveImages # 44: 0.34 sec
Failed to write measurements to database
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20150908201926_86986821ac927726b9645352f010bacc8b71671e/cellprofiler/modules/exporttodatabase.py", line 3176, in write_data_to_db
    disp_columns.append((rtbl_name,self.truncate_string_for_display(stmt%tuple(row_values[0]))))
IndexError: list index out of range
Error detected during run of module ExportToDatabase
Traceback (most recent call last):
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20150908201926_86986821ac927726b9645352f010bacc8b71671e/cellprofiler/pipeline.py", line 1830, in run_with_yield
    self.run_module(module, workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20150908201926_86986821ac927726b9645352f010bacc8b71671e/cellprofiler/pipeline.py", line 2078, in run_module
    module.run(workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20150908201926_86986821ac927726b9645352f010bacc8b71671e/cellprofiler/modules/exporttodatabase.py", line 1756, in run
    self.write_data_to_db(workspace)
  File "/imaging/analysis/CPClusterSingle/CellProfiler-2.0/redhat_6/20150908201926_86986821ac927726b9645352f010bacc8b71671e/cellprofiler/modules/exporttodatabase.py", line 3176, in write_data_to_db
    disp_columns.append((rtbl_name,self.truncate_string_for_display(stmt%tuple(row_values[0]))))
IndexError: list index out of range
```

**Comment by dlogan** [comment] 2016-01-11 16:52
Should I just hit resubmit for that task?

BTW the first task initially reported an error (some Java dependency issue, IIRC), but we hit resubmit and seemed to have fixed it.

**Comment by LeeKamentsky** [comment] 2016-01-11 18:52
This is, on one hand, a duplicate of #19 and on the other, a bug in CellProfiler (the stack trace). Looking at the stack trace, I think it will do the same thing if you resubmit - my guess is that there are no objects in the image and the bug happens because of that and because the pipeline has the ExportToDatabase module's window shown (open eyeball). The bug happens when ExportToDatabase tries to make up a line to display out of the measurements for the first object in the image set and there is no first object - there's a check to see if the eyeball is open and then, the bug happens.

A work-around is to do "Hide all Windows" and then re-create the batch file and I am betting the bug doesn't happen.

**Closed as completed by LeeKamentsky** 2016-01-11 18:52 UTC
Labels: bug, help wanted
